version: 0.0
os: linux
files:
  - source: /
    destination: ~/app/joes-angular-site/src
  AfterInstall:
    - location: stop.sh
      runas: root
  ApplicationStart:
    - location: start.sh
      runas: root